name: Publish to npm

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version
          registry-url: 'https://registry.npmjs.org/'
      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install  # Or npm install

      - name: Build
        run: yarn build  # Or npm run build

      - name: Publish to npm
        run: yarn npm publish --access public  # Or npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
